### ISSUE TITLE
creating prediction without having val files

### ISSUE THREAD

**Issue by aminrezaei-img** [juglab/EmbedSeg#11]
Hi, 
I am trying to create/generate prediction (part 3) but my dataset lacks validation files which prevent me from going further.
I was wondering is there a specific function or code that can be implemented to tackle the issue or by default, validation files are required to generate prediction?

**Comment by MLbyML** [comment]
Hello @aminrezaei-img 
Thanks for looking into EmbedSeg.
In general, that problem was not expected to arise since we try to check if there were GT instances defined alongside the validation images (for example, **[here](https://github.com/juglab/EmbedSeg/blob/a2b846176e3b04f217fef37d4673503d02af5dfb/EmbedSeg/test.py#L164)**). 
Could you please share your `03-predict.ipynb` notebook as well? Thanks!

**Comment by aminrezaei-img** [comment]
thank you for your reply, the issue is resolved, it was more of a directory issue.
