### ISSUE TITLE
Where is cmap_60.npy?

### ISSUE THREAD

**Issue by r-matsuzaka** [juglab/EmbedSeg#16]
Hello again.

I have a question about [your elaborate notebook](https://github.com/juglab/EmbedSeg/blob/main/examples/2d/bbbc010-2012/01-data.ipynb).
I get stacked one section when loading `cmap_60.npy`.

When I tried to load it, I got `FileNotFoundError: [Errno 2] No such file or directory: '../../../cmaps/cmap_60.npy'`.

How can I prepare it?

**Comment by ryo-matsuzaka** [comment]
Sorry I found https://github.com/juglab/EmbedSeg/tree/main/cmaps

**Comment by r-matsuzaka** [comment]
Sorry I found it https://github.com/juglab/EmbedSeg/tree/main/cmaps

**Comment by r-matsuzaka** [comment]
Sorry but `cmap_60.npy` is not created in the notebook?

**Comment by MLbyML** [comment]
Hello @r-matsuzaka Currently we created the color map once, by running this method **[here](https://github.com/juglab/EmbedSeg/blob/50f23233cf9564ff443c67c45a611ce665571c12/EmbedSeg/utils/visualize.py#L12)** with  `n_colors=60` and provided it with the repository. 
But, feel free to generate newer color maps with a larger `n_colors` and using them instead of `cmap_60.npy`.

**Comment by r-matsuzaka** [comment]
@MLbyML 
Thank you very much for your reply!
I understood:)
