### ISSUE TITLE
License and general questions

### ISSUE THREAD

**Issue by seekingdeep** [juglab/EmbedSeg#9]
embedseg seems promising,

- why not use bsd or apache for license
- how does embedseg compares to DenoiSeg in **segmenting connected components**, performance, efficiency, etc...

**Comment by MLbyML** [comment]
Hi @seekingdeep 
Thanks for looking into EmbedSeg. 

Regarding the second question about comparisons with **[DenoiSeg](https://arxiv.org/abs/2005.02987)**, since there the network is trained for a semantic task (i.e. trained to predict the pixel class) and addresses instance segmentation by extracting connected components during post processing,  this would generally under-perform methods where the network is trained directly for instance segmentation, speaking from my experience.  

For example: **[AP scores for IoU threshold = 0.5](0.801±0.001)** for alpha best configuration using all images (3800) as quoted by Denoiseg is **0.801±0.001** (in comparison, instance segmentation methods generally perform at ~0.86 on the same dataset!)

The benefits of methods addressing semantic segmentation on the other hand is a simplified architecture,  more intuitive methodology and more robust training. 
 
Regarding the first question, we re-used and adapted code by Neven et al, 2019 and so wanted to use the same license file as used by them!

**Comment by seekingdeep** [comment]
Thanks
